#default config options, the version of the file in the jar never changes, so that if server
#owners delete the file from the /plugins/LotteryPlugin folder it can be recreated from default settings
# You can set the time interval by using these patterns; d for days, mo for months, hr for hours, m for minutes
# Example; interval: 3mo, this would mean the lottery lasts three months
interval: 7d

# This decides whether to restart the lottery if one ends upon restart or not
# So if the lottery ends, and you restart the server, this decides if you want the plugin to setup a new one for you
# Use false if you do not want it to be automatic, or true if you do
auto-start: true

# This sets the standard price to purchase a ticket to play the lottery.
# This number is added to the lottery pull
#
ticket-price: 300

# The minimum price the lottery is to begin at
# Everytime a player purchases a ticket, the ticket price is added to this number
lottery-pull: 3000

# The interval in which the reminder about the lottery running should be sent
# This follows the same pattern as the interval setting
broadcast-interval: 1m

# This is the prefix the plugin will show in chat
plugin-prefix: "&8&l[&bLottoPlugin&8&l] "

# This is the format that messages broadcast by this plugin follow
# Example: &b&l%message%
# %message% is a placeholder for the content of the message
# This will display as the plugin-prefix + %message% in chat
chat-format: "&b%message%"

# Lottery winning message
# This decide how the message will look when a player wins the lottery
# Use %player% as a placeholder for the winning player.
win-lottery-message: "&a%player% &bhas won the lottery!"