#default config options, the version of the file in the jar never changes, so that if server
#owners delete the file from the /plugins/LotteryPlugin folder it can be recreated from default settings
# You can set the time interval by using these patterns; d for days, mo for months, hr for hours, m for minutes
# Example; interval: 3mo, this would mean the lottery lasts three months
interval: 7d

# This sets the standard price to purchase a ticket to play the lottery.
# This number is added to the lottery pull
#
ticket-price: 300

# The minimum price the lottery is to begin at
# Everytime a player purchases a ticket, the ticket price is added to this number
lottery-pull: 3000

# The interval in which the reminder about the lottery running should be sent
# This follows the same pattern as the interval setting
broadcast-interval: 1m

# This is the format that messages broadcast by this plugin follow
# Example: &8&l[&bLottoPlugin&8&l] &b&l%message%
# %message% is a placeholder for the content of the message
chat-format: &8&l[&bLottoPlugin&8&l] &b&l%message%