#default config options, the version of the file in the jar never changes, so that if server
#owners delete the file from the /plugins/LotteryPlugin folder it can be recreated from default settings
# You can set the time interval by using these patterns; d for days, mo for months, hr for hours, m for minutes
# Example; interval: 3mo, this would mean the lottery lasts three months
interval: 7d