name: LottoPlugin
version: 1.0.0
main: me.iblitzkriegi.lottoplugin.LottoPlugin
author: iBlitzkriegi
description: Lottery Plugin
commands:
  lottery:
    description: Allows administrators to have full control over the lottery
  buyticket:
    description: The command to purchase a ticket

